{
    "MetaData" : {
        "ParserVersion" : "17",
        "UpdateVersion" : "1",
        "UpdateArticleKey" : "",
        "CloudUpdateTimeUTC" : "2024-01-24 13:22:33"
    },
    "ControlSchemes" : [
        {
            "Name" : "Regss",
            "BuiltIn" : false,
            "Selected" : true,
            "IsBookMarked" : false,
            "IsCategoryVisible" : false,
            "KeyboardLayout" : "",
            "GameControls" : [
                {
                    "$type" : "Pan, Bluestacks",
                    "Type" : "Pan",
                    "Tweaks" : 16450,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 77.65,
                    "Y" : 50.0,
                    "LookAroundX" : -1.0,
                    "LookAroundY" : -1.0,
                    "LButtonX" : 81.54,
                    "LButtonY" : 73.85,
                    "Sensitivity" : 4.75,
                    "SensitivityRatioY" : 1.189473684,
                    "GamepadSensitivity" : 1.0,
                    "IsLookAroundEnabled" : true,
                    "IsShootOnClickEnabled" : true,
                    "MouseAcceleration" : false,
                    "KeyStartStop" : "E",
                    "KeyStartStop_alt1" : "",
                    "KeySuspend" : "",
                    "KeySuspend_alt1" : "",
                    "KeyLookAround" : "",
                    "KeyLookAround_alt1" : "",
                    "KeyAction" : "MouseLButton",
                    "GamepadStick" : "",
                    "IsCrosshairEnabled" : true,
                    "CrosshairX" : 50.05,
                    "CrosshairY" : 50.05,
                    "CrosshairType" : "Dot",
                    "CrosshairSize" : 1.9,
                    "CrosshairOpacity" : 100.0,
                    "CrosshairColor" : "#ff0000",
                    "CrosshairImage" : "",
                    "CrosshairShowOnOverlayExpr" : "",
                    "LButtonXExpr" : "",
                    "LButtonYExpr" : "",
                    "LButtonXOverlayOffset" : "",
                    "LButtonYOverlayOffset" : "",
                    "LButtonShowOnOverlayExpr" : "",
                    "LookAroundXExpr" : "",
                    "LookAroundYExpr" : "",
                    "LookAroundXOverlayOffset" : "",
                    "LookAroundYOverlayOffset" : "",
                    "LookAroundShowOnOverlayExpr" : "",
                    "Left" : 250.0,
                    "Right" : 250.0,
                    "Top" : 1000.0,
                    "Bottom" : 1000.0,
                    "ActivationTimeMs" : 40,
                    "Speed" : 10.0,
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Tap, Bluestacks",
                    "Type" : "Tap",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 95.3,
                    "Y" : 29.09,
                    "Key" : "MouseRButton",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Tap, Bluestacks",
                    "Type" : "Tap",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 87.88,
                    "Y" : 29.43,
                    "Key" : "C",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Tap, Bluestacks",
                    "Type" : "Tap",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 80.55,
                    "Y" : 29.99,
                    "Key" : "Z",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Tap, Bluestacks",
                    "Type" : "Tap",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 95.66,
                    "Y" : 11.91,
                    "Key" : "Space",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Tap, Bluestacks",
                    "Type" : "Tap",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 92.53,
                    "Y" : 85.56,
                    "Key" : "R",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Tap, Bluestacks",
                    "Type" : "Tap",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 87.58,
                    "Y" : 94.59,
                    "Key" : "1",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Tap, Bluestacks",
                    "Type" : "Tap",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 91.96,
                    "Y" : 93.81,
                    "Key" : "2",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Tap, Bluestacks",
                    "Type" : "Tap",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 96.41,
                    "Y" : 93.81,
                    "Key" : "3",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Tap, Bluestacks",
                    "Type" : "Tap",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 59.74,
                    "Y" : 95.03,
                    "Key" : "Alt",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Tap, Bluestacks",
                    "Type" : "Tap",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 71.08,
                    "Y" : 50.05,
                    "Key" : "F",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Tap, Bluestacks",
                    "Type" : "Tap",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 96.97,
                    "Y" : 41.48,
                    "Key" : "F",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Tap, Bluestacks",
                    "Type" : "Tap",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 91.03,
                    "Y" : 41.47,
                    "Key" : "G",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Tap, Bluestacks",
                    "Type" : "Tap",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 3.12,
                    "Y" : 79.18,
                    "Key" : "5",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Tap, Bluestacks",
                    "Type" : "Tap",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 74.24,
                    "Y" : 22.57,
                    "Key" : "4",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Tap, Bluestacks",
                    "Type" : "Tap",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 16.66,
                    "Y" : 42.71,
                    "Key" : "X",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Tap, Bluestacks",
                    "Type" : "Tap",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 1.74,
                    "Y" : 49.96,
                    "Key" : "Tab",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Dpad, Bluestacks",
                    "Type" : "Dpad",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 39.07,
                    "Y" : 31.14,
                    "KeyUp" : "W",
                    "KeyUp_alt1" : "",
                    "KeyDown" : "S",
                    "KeyDown_alt1" : "",
                    "KeyLeft" : "A",
                    "KeyLeft_alt1" : "",
                    "KeyRight" : "D",
                    "KeyRight_alt1" : "",
                    "KeySpeedModifier1" : "",
                    "KeySpeedModifier1_alt1" : "",
                    "KeySpeedModifier2" : "",
                    "KeySpeedModifier2_alt1" : "",
                    "GamepadStick" : "",
                    "XRadius" : 9.0,
                    "XRadius1" : 0.0,
                    "XRadius2" : 0.0,
                    "DeadzoneRadius" : 0.0,
                    "Speed" : 1000.0,
                    "ActivationSpeed" : 200.0,
                    "ActivationTime" : 50,
                    "DpadExpiryTime" : 0,
                    "AnalogType" : 0,
                    "DpadTitle" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "Tap, Bluestacks",
                    "Type" : "Tap",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 80.61,
                    "Y" : 22.63,
                    "Key" : "MouseXButton1",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                },
                {
                    "$type" : "TapRepeat, Bluestacks",
                    "Type" : "TapRepeat",
                    "Tweaks" : 0,
                    "Exclusive" : false,
                    "ExclusiveDelay" : 200,
                    "XExpr" : "",
                    "YExpr" : "",
                    "XOverlayOffset" : "",
                    "YOverlayOffset" : "",
                    "StartCondition" : "",
                    "EnableCondition" : "",
                    "ShowOnOverlay" : true,
                    "X" : 54.78,
                    "Y" : 73.44,
                    "Count" : 99,
                    "Delay" : 5,
                    "RepeatUntilKeyUp" : true,
                    "Key" : "F1",
                    "Key_alt1" : "",
                    "GuidanceCategory" : "",
                    "Guidance" : {

                    }
                }
            ],
            "Images" : [

            ]
        }
    ],
    "Strings" : {

    }
}
